### ISSUE TITLE
Port to AVX2 and AVX-512

### ISSUE THREAD

**Issue by lemire** [lemire/fastvalidate-utf-8#6]
This could be made much faster with wider registers.

**Comment by KWillets** [comment]
A sample for AVX512:

`
void checkContinuation(__m512i counts,
                                     __m512i previous_counts,
                                     __mmask64 *has_error) {

  __m512i right1 = _mm512_subs_epu8(_mm512_alignr_epi8(counts, previous_counts,64 - 1),
				 _mm512_set1_epi8(1));
  __m512i sum = _mm512_add_epi8(counts, right1);

  __m512i right2 = _mm512_subs_epu8(_mm512_alignr_epi8(sum, previous_counts,64 - 2),
				 _mm512_set1_epi8(2));
   sum = _mm512_add_epi8(sum, right2);

   // overlap || underlap
   // sum > count && count > 0 || !(sum > count) && !(count > 0)
   // (sum > count) == (count > 0)
   __mmask64 overunder = 
        _mm512_cmpeq_epu8_mask(sum,counts) ^ 
        _mm512_cmpeq_epu8_mask(counts, _mm512_setzero_si512());
   
   *has_error |= ~overunder;
}
`
Mostly s/_mm_/_mm512_/g and s/__m128i/__m512i/g.  has_error has to change to a mask though.

**Comment by pcordes** [comment]
Yup, AVX-512 natively has unsigned compare, and can save some ANDs with masked-compare into another mask.  (Compilers are typically decent at doing this optimization for you with intrinsics)

The cheapness of branching on a mask being non-zero means it might be worth adding an early-out.  But I guess for most use-cases, invalid data is very much the exception, and hurting the valid case at all to return early for the invalid case isn't worth it.

----

The AVX2 in-lane behaviour of `vpalignr` is an obstacle to straightforward widening to `__m256i`, though.  http://felixcloutier.com/x86/PALIGNR.html has a diagram for 256-bit.  We might want to do some unaligned loads to get data where we want it, instead of shuffling.  e.g. maybe advance by 28 bytes per iteration instead of 32, and shuffle something from the end back to the front with `vpermd`?

AVX-512 has a lane-crossing byte shuffle in `vpermb`, but that requires AVX512VBMI ([cannonlake, but not SKX or KNL](https://en.wikipedia.org/wiki/AVX-512#CPUs_with_AVX-512)), and it costs multiple shuffle uops so it's not ideal.  (`vpermw` is multiple uops on SKX, `vpermb` will probably be at least as many on Cannonlake.)  2-source shuffles like `vpermt2b` are very powerful but probably even slower.

**Comment by lemire** [comment]
> The AVX2 in-lane behaviour of vpalignr is an obstacle to straightforward widening to __m256i, though. 

I am optimistic. I expect that it will cost a couple of extra instructions to muck up the lanes... but we are currently issuing around 48 muops per vector register... So we can afford to spend a lot of instructions on getting the lanes properly populated.

Extra loads are probably fine, as you suggest. We probably have load capacity to spare.

Chances are good that we can double the speed (almost) by going to AVX2.

**Comment by KWillets** [comment]
The overriding issue is that basic shift or alignr operations will be possibly twice or more slower (in instruction counts, and latency/throughput).  However we only do four alignr's, so it may not be much overhead.  

Another option is to process 2-4 separate streams in 128-bit subregisters, by splitting the input into substrings and patching the edges.  We only need to look 4 bytes behind each split boundary to carry continuations properly.

**Comment by lemire** [comment]
> The overriding issue is that basic shift or alignr operations will be possibly twice or more slower (in instruction counts, and latency/throughput).

My expectation is that we are doubling the cost of something that is nearly negligible.  We are at 0.7 to 0.8 cycles with 128-bit registers, so I think we ought to achieve 0.4 cycles with 256-bit registers and 0.2 cycles with 512-bit registers. It may be hard to get exactly 0.2 cycles with current AVX-512 processors, but we ought to be able to get close (~0.25 cycles?).

Of course, one just needs to implement it to know.

**Comment by KWillets** [comment]
PR12 was the last thing I was worried about before porting; I didn't want to have to move any tricky deltas across SIMD versions afterwards.

**Comment by lemire** [comment]
Port done. Closing.
